### ISSUE TITLE
AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE when trying Fleet Provisioning

### ISSUE THREAD

**Issue by setch3000** [aws-samples/aws-iot-fleet-provisioning#10]
Hi,
I am trying Fleet Provisioning on Cloud 9 (Amazon Linux) and need your help, since I have an error as below.
I've installed all python dependencies (pip3 install -r requirements.txt).
I've made Fleet provisioning template and bootstrap certificate, and updated config.ini accordingly.

I am using awsiotsdk as below.
**awsiotsdk in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (1.5.2)
awscrt==0.9.10 in /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages (from awsiotsdk) (0.9.10)**

But, I have below error:
**awscrt.exceptions.AwsCrtError: AwsCrtError(name='AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE', message='TLS (SSL) negotiation failed', code=1029)**

Could you please let me know if there is any solution for this error?

sa:~/environment/aws-iot-fleet-provisioning (master) $ python3 main.py
                 ______   __                   __ 
                / ____/  / /  ___     ___     / /_
               / /_     / /  / _ \   / _ \   / __/
              / __/    / /  /  __/  /  __/  / /_  
             /_/      /_/   \___/   \___/   \__/  
                                                  

    ____                  _      _             _            
   / __ \_________ _   __(_)____(_)___  ____  (_)___  ____ _
  / /_/ / ___/ __ \ | / / / ___/ / __ \/ __ \/ / __ \/ __ `/
 / ____/ /  / /_/ / |/ / (__  ) / /_/ / / / / / / / / /_/ / 
/_/   /_/   \____/|___/_/____/_/\____/_/ /_/_/_/ /_/\__, /  
                                                   /____/   

                                                             
                                                             
 ____________________________________________________________
/_____/_____/_____/_____/_____/_____/_____/_____/_____/_____/
                                                             
                                                             

##### CONNECTING WITH PROVISIONING CLAIM CERT #####
Connecting to a9y1ao0iqy0he.iot.us-east-1.amazonaws.com with client ID '1234567-abcde-fghij-klmno-1234567abc-TLS350'...
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    run_provisioning(isRotation=False)
  File "main.py", line 73, in run_provisioning
    provisioner.get_official_certs(callback)
  File "/home/ec2-user/environment/aws-iot-fleet-provisioning/provisioning_handler.py", line 160, in get_official_certs
    return asyncio.run(self.orchestrate_provisioning_flow(callback))
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ec2-user/environment/aws-iot-fleet-provisioning/provisioning_handler.py", line 164, in orchestrate_provisioning_flow
    self.core_connect()
  File "/home/ec2-user/environment/aws-iot-fleet-provisioning/provisioning_handler.py", line 101, in core_connect
    connect_future.result()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AwsCrtError(name='AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE', message='TLS (SSL) negotiation failed', code=1029)

**Comment by RaleighSF** [comment]
Closing issue resolved by using the "-ats" endpoint instead of the "iot" endpoint.
a9y1ao0iqy0he.iot.us-east-1.amazonaws.com --> a9y1ao0iqy0he**-ats**.iot.us-east-1.amazonaws.com

**Comment by setch3000** [comment]
Thank you very much.
