### ISSUE TITLE
regarding cert rotation policy

### ISSUE THREAD

**Issue by satishnalla** [aws-samples/aws-iot-fleet-provisioning#12]
this article helps to create workflow for device provisioning....i have one question regarding cert rotation. 
do we need to create two polices AWS cloud one for initial provisioning template and other for cert rotation template ...

On device side, to subscribe for cert rotation topic command , once it receives notification, it initiates with cert rotation template ...is this correct?

Also, execution time limitation  on pre-validation lambda hook , it is mentioned as 5 sec as per document, Is it possible to increase this ?

**Comment by RaleighSF** [comment]
Thanks for the feedback and questions.

You will need need to create another policy for certificate rotation. This policy should include the usual access a device/system will need to conduct business but also the topics necessary ($aws/...) to request additional credentials (at the time of rotation.

Yes, The device will receive the notification from the cloud service to rotate and would then need to respond by initiating the flow to obtain a new certificate. After validation, you'd likely want to invalidate the previous certificate.

The 5 second lambda return is currently a hard limit for that transaction.

You might also enjoy an alternative repo: [https://github.com/aws-samples/automated-iot-fleet-provisioning-by-claim](https://github.com/aws-samples/automated-iot-fleet-provisioning-by-claim) which fleshes out the cert rotation a bit more, including sample client code and provisioning templates. (with script support).

**Comment by satishnalla** [comment]
Thanks for the response
