### ISSUE TITLE
AWS generated certificates expiry clarifications

### ISSUE THREAD

**Issue by satishnalla** [aws-samples/aws-iot-fleet-provisioning#15]
We are using device provisioning workflow provided by AWS i.e., provisioning by claim method. Regarding certificate expiry , we would like to understand whether it is possible to set other than default expiry i.e., year 2049 ...because we have requirement to keep it short life span for certificates used by IotDevices

Appreciate your help and response on this clarification

**Comment by RaleighSF** [comment]
@satishnalla - Yes. We have set up a custom cert provisioning mechanism which allows you to set an expiration of ANY date. It is honored as part of an attribute of a THING, and is explained more in detail through our automated repo here: See Cert Expiry: https://github.com/aws-samples/automated-iot-fleet-provisioning-by-claim
