### ISSUE TITLE
Rotation Template

### ISSUE THREAD

**Issue by kcfdaniel** [aws-samples/aws-iot-fleet-provisioning#3]
Hi there, I'm interested in using AWS IoT Fleet Provisioning.  Your sample helps a lot!
I see that recently you've made an update regarding certificate rotation, and somehow one has to have a "rotation template", may I know how to create such a template?  I'm just a beginner in AWS, so I'm looking for a way to do it with AWS console.  I'd also like to know if there's a way to create "rotation template" with CloudFormation.

thanks a lot!

**Comment by RaleighSF** [comment]
Thanks for the note, and feedback! I have updated the repo to include
sample assets for the validation lambdas, and provisioning templates as
requested. I will follow-up with a CF solution in the coming weeks to help
guide additional adoption. Thanks for your interest!
