### ISSUE TITLE
Missing subscribe for the /accepted response topics?

### ISSUE THREAD

**Issue by MartinMReed** [aws-samples/aws-iot-fleet-provisioning#6]
I can’t find anywhere that the /accepted topics are subscribed to. It has the /rejected topics subscribed for the errors, but doesn’t have the /accepted topics for the success. Is this a bug or does the broker handle these provisioning call responses special?

**Comment by RaleighSF** [comment]
Hey Marty, you can certainly subscribe to corresponding /accepted topics to get the response payload directly from each call (CreateKey/RegisterThing, etc). Alternatively, the sample implementation defines a common callback to capture all responses and then essentially analyze/switches the response payload to direct the orchestration accordingly. Is that what you were asking, essentially?

**Comment by MartinMReed** [comment]
With MQTT you're not supposed to get any messages over any topics unless you've called subscribe to that topic. The AWS broker seems to not be following that with these provisioning topics, and is either auto-subscribing any client that publishes to them... or it has special logic to send a direct response to the client instead of the standard broadcast to all subscribers. If it is a direct response, that is certainly more secure... but it's not standard, and I don't see this mentioned anywhere in the docs.

https://docs.aws.amazon.com/iot/latest/developerguide/fleet-provision-api.html

This sample does get the response, so it must just be the docs are not correct / not clear about the actual behavior. Thanks Raleigh.
